#!/bin/bash
# MintyForge - Main script
# Utility for Linux Mint Cinnamon configuration and setup

LOGFILE="logs/mintyforge.log"
mkdir -p logs

# Disable suspend & screensaver temporarily
gsettings set org.cinnamon.settings-daemon.plugins.power sleep-inactive-ac-timeout 0
gsettings set org.cinnamon.settings-daemon.plugins.power sleep-inactive-battery-timeout 0
gsettings set org.cinnamon.desktop.screensaver lock-enabled false

sudo apt update -y && sudo apt upgrade -y 

main_menu() {
  clear
  echo "=== MintyForge ==="
  echo "1) Update & Upgrade"
  echo "2) Install APT packages"
  echo "3) Remove unwanted APT packages"
  echo "4) Install Flatpaks"
  echo "5) Install User Themes (GTK, Icons, Cursors)"
  echo "6) Install System Themes + Greeter"
  echo "7) Configure Drivers"
  echo "8) Configure Qt Apps (setup + theme)"
  echo "9) Run Distroscript"
  echo "0) Exit"
  echo
  read -p "Choose an option: " choice

  case $choice in
    1) sudo apt update -y && sudo apt upgrade -y ;;
    2) ./scripts/apt_install ;;
    3) ./scripts/apt_remove ;;
    4) ./scripts/flatpak_install ;;
    5) ./scripts/themes_user;;
    6) ./scripts/themes_system;;
    7) ./scripts/drivers ;;
    8) ./scripts/qt_setup && ./scripts/qt_apply ;;
    9) ./scripts/distroscript ;;
    0) exit 0 ;;
    *) echo "Invalid option" ;;
  esac
}

while true; do
  main_menu | tee -a "$LOGFILE"
  read -p "Press Enter to continue..."
done
